// Push Notification Utilities
import { apiRequest } from '@/lib/queryClient';

export interface PushSubscriptionData {
  endpoint: string;
  p256dhKey: string;
  authKey: string;
  userAgent: string;
}

class PushNotificationService {
  private swRegistration: ServiceWorkerRegistration | null = null;
  
  // Public VAPID key - this will be generated by the backend
  private readonly vapidPublicKey = 'BEl62iUYgUivxIkv69yViEuiBIa40HcCeAE';

  async initialize(): Promise<boolean> {
    if (!this.isSupported()) {
      console.warn('Push notifications are not supported in this browser');
      return false;
    }

    try {
      // Register service worker
      this.swRegistration = await navigator.serviceWorker.register('/sw.js', {
        scope: '/',
      });

      console.log('Service Worker registered successfully:', this.swRegistration);

      // Wait for service worker to be ready
      await navigator.serviceWorker.ready;
      return true;
    } catch (error) {
      console.error('Service Worker registration failed:', error);
      return false;
    }
  }

  isSupported(): boolean {
    return (
      'serviceWorker' in navigator &&
      'PushManager' in window &&
      'Notification' in window
    );
  }

  async getPermissionStatus(): Promise<NotificationPermission> {
    if (!('Notification' in window)) {
      return 'denied';
    }
    return Notification.permission;
  }

  async requestPermission(): Promise<boolean> {
    if (!this.isSupported()) {
      return false;
    }

    const permission = await Notification.requestPermission();
    return permission === 'granted';
  }

  async subscribe(): Promise<PushSubscriptionData | null> {
    if (!this.swRegistration) {
      throw new Error('Service Worker not registered. Call initialize() first.');
    }

    if (Notification.permission !== 'granted') {
      const granted = await this.requestPermission();
      if (!granted) {
        return null;
      }
    }

    try {
      // Convert VAPID key to Uint8Array
      const vapidKey = this.urlBase64ToUint8Array(this.vapidPublicKey);

      const subscription = await this.swRegistration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: vapidKey,
      });

      const subscriptionData: PushSubscriptionData = {
        endpoint: subscription.endpoint,
        p256dhKey: this.arrayBufferToBase64(subscription.getKey('p256dh')!),
        authKey: this.arrayBufferToBase64(subscription.getKey('auth')!),
        userAgent: navigator.userAgent,
      };

      // Save subscription to backend
      await this.saveSubscriptionToServer(subscriptionData);

      return subscriptionData;
    } catch (error) {
      console.error('Failed to subscribe for push notifications:', error);
      return null;
    }
  }

  async unsubscribe(): Promise<boolean> {
    if (!this.swRegistration) {
      return false;
    }

    try {
      const subscription = await this.swRegistration.pushManager.getSubscription();
      if (subscription) {
        // Remove subscription from server
        await this.removeSubscriptionFromServer(subscription.endpoint);
        
        // Unsubscribe from push manager
        await subscription.unsubscribe();
      }
      return true;
    } catch (error) {
      console.error('Failed to unsubscribe from push notifications:', error);
      return false;
    }
  }

  async isSubscribed(): Promise<boolean> {
    if (!this.swRegistration) {
      return false;
    }

    try {
      const subscription = await this.swRegistration.pushManager.getSubscription();
      return subscription !== null;
    } catch (error) {
      console.error('Failed to check subscription status:', error);
      return false;
    }
  }

  async getSubscription(): Promise<PushSubscription | null> {
    if (!this.swRegistration) {
      return null;
    }

    try {
      return await this.swRegistration.pushManager.getSubscription();
    } catch (error) {
      console.error('Failed to get subscription:', error);
      return null;
    }
  }

  private async saveSubscriptionToServer(subscriptionData: PushSubscriptionData): Promise<void> {
    await apiRequest('/api/push/subscribe', {
      method: 'POST',
      body: JSON.stringify(subscriptionData),
      headers: {
        'Content-Type': 'application/json',
      },
    });
  }

  private async removeSubscriptionFromServer(endpoint: string): Promise<void> {
    await apiRequest('/api/push/unsubscribe', {
      method: 'POST',
      body: JSON.stringify({ endpoint }),
      headers: {
        'Content-Type': 'application/json',
      },
    });
  }

  // Utility functions
  private urlBase64ToUint8Array(base64String: string): Uint8Array {
    const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
    const base64 = (base64String + padding)
      .replace(/-/g, '+')
      .replace(/_/g, '/');

    const rawData = window.atob(base64);
    const outputArray = new Uint8Array(rawData.length);

    for (let i = 0; i < rawData.length; ++i) {
      outputArray[i] = rawData.charCodeAt(i);
    }
    return outputArray;
  }

  private arrayBufferToBase64(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    let binary = '';
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return window.btoa(binary);
  }

  async sendTestNotification(): Promise<boolean> {
    try {
      const response = await apiRequest('/api/push/test', {
        method: 'POST',
      });
      return response.success;
    } catch (error) {
      console.error('Failed to send test notification:', error);
      return false;
    }
  }
}

// Export singleton instance
export const pushNotifications = new PushNotificationService();