export interface Article {
  slug: string;
  question: string;
  answer: string;
}

export interface Category {
  slug: string;
  title: string;
  icon: string;
  description: string;
  articles: Article[];
}

export const SUPPORT_CATEGORIES: Category[] = [
  {
    slug: "getting-started",
    title: "Getting Started",
    icon: "🚀",
    description: "New to LiveSwell? Start here.",
    articles: [
      {
        slug: "search-surf-spot",
        question: "How do I search for a surf spot?",
        answer:
          "Tap the search bar at the top of the Explore screen and type any beach, point break, reef, or general coastal area. LiveSwell covers 218+ spots across every surfing continent. As you type, matching spots appear instantly — tap one to load its live conditions. If your exact spot isn't listed, try searching the nearest town or the broader region; the closest covered spot is usually within a short drive.",
      },
      {
        slug: "save-favorite",
        question: "How do I save a spot to my favorites?",
        answer:
          "Open the conditions page for any spot and tap the star icon (⭐) in the top-right corner of the screen. The spot is saved to your Favorites tab immediately. Your favorites persist across devices as long as you're signed in with the same account. To remove a spot, tap the star again — it toggles off.",
      },
      {
        slug: "wave-height-meaning",
        question: "What does the wave height number mean?",
        answer:
          "The wave height shown is the significant wave height — the average of the top one-third of waves measured at the nearest NOAA buoy. In surfing terms this is roughly the face height of the sets you'd actually be riding, though local bathymetry and swell direction can affect how waves break at your specific spot. A 4 ft reading at the buoy typically translates to 3–5 ft faces at a beach break, and potentially bigger at a reefing point break.",
      },
      {
        slug: "data-update-frequency",
        question: "How is the data updated?",
        answer:
          "NOAA buoy readings are updated every 30 minutes. Tide predictions are pre-computed daily and are highly accurate. The AI surf summary regenerates whenever you open the conditions page if the underlying data has changed since your last visit. Wind data refreshes every 30 minutes alongside the buoy readings. The conditions badge (Epic / Good / Fair / Poor) recalculates automatically each time new data arrives.",
      },
    ],
  },
  {
    slug: "conditions-data",
    title: "Conditions Data",
    icon: "🌊",
    description: "Understanding wave, wind, and swell readings.",
    articles: [
      {
        slug: "wave-data-source",
        question: "Where does the wave data come from?",
        answer:
          "LiveSwell pulls wave height, swell period, and swell direction from NOAA's National Data Buoy Center (NDBC) — a network of over 1,350 offshore and coastal buoys maintained by the U.S. government. For spots outside the NDBC coverage area (international breaks), we supplement with Open-Meteo Marine forecast data. You can see which buoy is assigned to any spot in the detailed data panel.",
      },
      {
        slug: "swell-period",
        question: "What is swell period and why does it matter?",
        answer:
          "Swell period (measured in seconds) is the time between successive wave crests passing a fixed point. A longer period means waves were generated by a distant, powerful storm and have organised into clean groundswell — these waves hold their energy all the way to shore and produce powerful, well-defined surf. A short period (under 8 seconds) usually means locally-generated wind swell: choppier, less powerful, and harder to time. As a rough guide: under 8s = choppy wind swell, 8–12s = decent swell, 12–16s = solid groundswell, 16s+ = long-period groundswell that can produce very powerful surf.",
      },
      {
        slug: "swell-direction",
        question: "What does swell direction mean for my break?",
        answer:
          "Swell direction is the compass bearing the swell is travelling from — so a 270° swell is coming from due west. Whether that's good for your break depends entirely on its orientation. A spot that faces southwest will light up on NW–W swell. A sheltered bay might need a more direct swell angle to wrap in. LiveSwell shows you the raw swell direction so you can judge it against your local knowledge. The conditions badge incorporates direction into its rating where possible.",
      },
      {
        slug: "two-buoys",
        question: "Why does my spot show two buoys?",
        answer:
          "Some spots are assigned a primary offshore buoy (farther out, shows open-ocean swell) and a secondary nearshore or coastal buoy (closer in, shows the swell as it approaches the break). The primary buoy gives you groundswell information; the nearshore buoy is more representative of what you'll actually see in the water. When both are available, LiveSwell displays both readings so you can compare them.",
      },
      {
        slug: "ai-summary-accuracy",
        question: "How accurate is the AI surf summary?",
        answer:
          "The AI summary is generated from real buoy data, tide tables, and wind readings — it's not generic text. It synthesises the numbers into a plain-English read of conditions at that moment. However, it cannot account for hyperlocal factors like sandbars, crowd, or how a specific break handles a given swell angle. Think of it as a knowledgeable friend reading the same data you see — helpful context, not a guarantee. Always cross-reference with local surf cams or knowledge for critical sessions.",
      },
    ],
  },
  {
    slug: "sms-alerts",
    title: "SMS Alerts",
    icon: "📱",
    description: "Set up and manage condition alerts.",
    articles: [
      {
        slug: "setup-alert",
        question: "How do I set up a condition alert?",
        answer:
          "Open the conditions page for the spot you want to track, then tap \"Set Alert\" (the bell icon). You'll be prompted to verify your phone number if you haven't already — enter your number, receive a one-time code by text, and confirm it. Then set your thresholds: minimum wave height, maximum wind speed, and any other criteria. LiveSwell will send you an SMS whenever conditions at that spot meet your criteria. The alert checks every 20 minutes.",
      },
      {
        slug: "alert-thresholds",
        question: "What thresholds can I set?",
        answer:
          "You can set a minimum wave height (in feet) and a maximum wind speed (in mph). When the buoy reports wave height at or above your minimum and wind speed at or below your maximum simultaneously, the alert fires. You can also specify a time window (e.g. only alert between 6am and noon) so you don't get woken up at 3am for perfect waves you can't surf.",
      },
      {
        slug: "stop-alerts",
        question: "How do I stop receiving alerts?",
        answer:
          "There are three ways: (1) Reply STOP to any LiveSwell SMS — this opts you out at the carrier level immediately. (2) Open the alert in the app and tap \"Delete Alert\". (3) Go to your profile → Notifications and toggle off SMS alerts entirely. If you used STOP and want to re-enable, you can do so from the disabled-alerts banner in the app or by replying START to the LiveSwell number.",
      },
      {
        slug: "missed-alert",
        question: "Why didn't I get an alert when conditions were good?",
        answer:
          "A few things to check: (1) Make sure your phone number is verified under Profile → Notifications. (2) Check that the alert is still active and hasn't been paused or deleted. (3) Confirm your thresholds — if you set 5 ft minimum but the buoy read 4.8 ft, the alert won't fire. (4) If you replied STOP to a previous LiveSwell message, SMS delivery is blocked at the carrier level — re-enable from the banner in the app. (5) Very occasionally NOAA buoys go offline; if the buoy shows no recent data, LiveSwell can't check conditions.",
      },
      {
        slug: "multiple-spots",
        question: "Can I set alerts for multiple spots?",
        answer:
          "Yes. You can create as many alerts as you like across different spots, or even multiple alerts for the same spot with different thresholds (e.g. one for dawn patrol, one for afternoon sessions). Each alert fires independently. You can review and manage all your active alerts from Profile → Notifications.",
      },
    ],
  },
  {
    slug: "tides-forecasts",
    title: "Tides & Forecasts",
    icon: "🌙",
    description: "Reading tide charts and forecast data.",
    articles: [
      {
        slug: "read-tide-chart",
        question: "How do I read the tide chart?",
        answer:
          "The tide chart shows the full tidal curve for the current day. The vertical axis is tide height in feet above mean lower low water (MLLW) — the baseline used by NOAA. The curve rises to high tides and dips to low tides throughout the day. Tap any point on the curve to see the exact height and time. High and low tide markers are labelled directly on the chart. The coloured vertical lines mark sunrise and sunset.",
      },
      {
        slug: "forecast-range",
        question: "How far ahead does the forecast go?",
        answer:
          "The wave and wind forecast extends 5 days from today. Tide predictions are pre-computed from astronomical models and are accurate for months ahead — the tide chart shows today plus the next few days. Beyond 5 days, forecast accuracy drops significantly for wave and wind data, so LiveSwell doesn't display it. For long-range swell planning (7–14 days), dedicated services like Surfline's Forecast Discussion are a useful complement.",
      },
      {
        slug: "sunrise-sunset-line",
        question: "What is the sunrise/sunset line on the tide chart?",
        answer:
          "The two vertical lines on the tide chart mark sunrise (yellow/orange) and sunset (blue/purple) times for that day at the spot's location. They're there to help you time your sessions — for example, to see whether the best low tide falls before sunrise (dawn patrol territory) or in the afternoon. The times are calculated from the spot's latitude and longitude and update daily.",
      },
    ],
  },
  {
    slug: "account-privacy",
    title: "Account & Privacy",
    icon: "🔐",
    description: "Managing your account and data.",
    articles: [
      {
        slug: "delete-account",
        question: "How do I delete my account?",
        answer:
          "To delete your LiveSwell account and all associated data, go to Profile → Privacy → Delete Account. You'll be asked to confirm. Once deleted, your favorites, alert settings, phone number, and usage history are permanently removed. This action cannot be undone. If you only want to stop receiving SMS alerts without deleting your account, you can manage that separately under Profile → Notifications.",
      },
      {
        slug: "data-collected",
        question: "What data does LiveSwell collect?",
        answer:
          "LiveSwell collects: (1) Your Replit account identifier and display name for authentication. (2) Your phone number if you choose to set up SMS alerts — stored only to deliver those alerts. (3) Your saved favorite spots and alert preferences. (4) Anonymous usage analytics (pages viewed, features used) to improve the app. We do not sell your data, share it with advertisers, or use it for any purpose beyond operating the app. Full details are in our Privacy Policy.",
      },
      {
        slug: "update-phone-number",
        question: "How do I update my phone number?",
        answer:
          "Go to Profile → Notifications → Phone Number. You can enter a new number and verify it with a one-time SMS code. Once verified, the new number replaces the old one for all your SMS alerts. If you previously opted out via STOP on the old number, that opt-out stays on the carrier side for that number — the new number starts fresh. If you have trouble updating your number, contact us using the form below.",
      },
    ],
  },
  {
    slug: "troubleshooting",
    title: "Troubleshooting",
    icon: "🔧",
    description: "Fix common issues quickly.",
    articles: [
      {
        slug: "no-data-available",
        question: "The app says \"no data available\" for my spot",
        answer:
          "This usually means the nearest NOAA buoy is temporarily offline or experiencing a data gap. NOAA buoys occasionally go offline for maintenance or due to weather damage. When this happens, LiveSwell has no real-time data to display and shows the no-data message rather than showing stale or fabricated readings. Try again in 30–60 minutes. If the issue persists for more than a few hours, the buoy may be down for maintenance — NOAA typically restores service within 24–48 hours.",
      },
      {
        slug: "sms-alerts-stopped",
        question: "My SMS alerts stopped working",
        answer:
          "Check these in order: (1) Open the app and look for a disabled-alerts banner — if you (or someone) replied STOP to a LiveSwell message, SMS is blocked at the carrier. Tap Re-enable in the banner. (2) Go to Profile → Notifications and confirm your alert is still active. (3) Check that your phone number is still verified — if you changed numbers, re-verify. (4) Make sure conditions actually met your thresholds since you last received an alert. (5) If none of these help, use the contact form below and include your phone number and the spot name.",
      },
      {
        slug: "conditions-not-updated",
        question: "The conditions haven't updated in a while",
        answer:
          "LiveSwell refreshes data every 30 minutes automatically when the app is open. If you suspect stale data, pull down on the conditions screen to force a manual refresh. If the timestamp still doesn't update, the buoy for that spot may be offline — this is a NOAA infrastructure issue, not something LiveSwell can fix. The timestamp shown is always the actual time of the last buoy reading, so you can tell exactly how fresh the data is.",
      },
      {
        slug: "app-slow",
        question: "The app is slow or not loading",
        answer:
          "Try these steps: (1) Hard-refresh the page (Cmd+Shift+R on Mac, Ctrl+Shift+R on Windows). (2) Check your internet connection — LiveSwell fetches live data, so a weak connection will slow it down. (3) Clear your browser cache if the issue persists after a refresh. (4) If you're on a slow mobile connection, the NOAA data fetch can take 3–5 seconds — this is normal. (5) If the app is completely unresponsive or showing errors, please use the contact form below with a description of what you see.",
      },
    ],
  },
];

export function getAllArticles(): Array<Article & { categorySlug: string; categoryTitle: string }> {
  return SUPPORT_CATEGORIES.flatMap(cat =>
    cat.articles.map(article => ({
      ...article,
      categorySlug: cat.slug,
      categoryTitle: cat.title,
    }))
  );
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return SUPPORT_CATEGORIES.find(c => c.slug === slug);
}
